---
- name: Obtener la contraseña del usuario admin
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: data

- name: Instalar plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: latest
    params: "{{ jenkins_params }}"
    url_password: "{{ data.stdout }}"
  with_items: "{{ jenkins_plugins }}"

- name: Reiniciar servicio Jenkins
  service: name=jenkins state=restarted