---
- name: Añadir URL de repositorio Jenkins al sistema
  get_url: url={{ jenkins_repo_url }} dest=/etc/yum.repos.d/jenkins.repo
  
- name: Importar clave pública de RPM de Jenkins
  rpm_key: key={{ jenkins_public_key_url }} state=present
  
- name: Instalar Jenkins y sus dependencias
  yum: name={{ item }} state=latest update_cache=yes
  with_items: '{{ jenkins_packages }}'
  
- name: Iniciar servicio Jenkins
  service: name=jenkins state=started enabled=yes